baykeproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include("baykeshop.urls")),

    *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
]

baykeshop/apps/shop/api/urls.py
'''
@file            :urls.py
@Description     :接口url
@Date            :2023/09/11 21:08:48
@Author          :幸福关中 && 轻编程
@version         :v1.0
@EMAIL           :1158920674@qq.com
@WX              :baywanyun
'''

from django.urls import path
from rest_framework.routers import DefaultRouter
from . import views

app_name = "shopapi"

router = DefaultRouter()

router.register('address', views.BaykeAddressViewSet, basename='address')

urlpatterns = [
    path(
        'create-cart/', 
        views.BaykeShopCartCreateAPIView.as_view(), 
        name='create-cart'
    ),
    path(
        'update-cart-num/', 
        views.BaykeShopCartUpdateNumAPIView.as_view(), 
        name='update-cart-num'
    ),
    path(
        'del-cart/', 
        views.BaykeShopCartUpdateNumAPIView.as_view(), 
        name='del-cart'
    ),
    path(
        'create-order/', 
        views.BaykeShopOrderCreateAPIView.as_view(), 
        name='create-order'
    ),
    path(
        'cash-order/', 
        views.BaykeShopOrderCashAPIView.as_view(), 
        name='cash-order'
    ),
    path(
        'confirm-receipt/', 
        views.ConfirmReceiptAPIView.as_view(), 
        name='confirm-receipt'
    ),
    *router.urls
]

baykeshop/urls.py
from django.urls import path, include
from tinymce.views import TinyMCEImageUpload

urlpatterns = [
    path('', include('baykeshop.apps.shop.urls')),
    path('article/', include('baykeshop.apps.article.urls')),
    path('system/', include('baykeshop.apps.system.urls')),
    path('user/', include('baykeshop.apps.user.urls')),
    path('captcha/', include('captcha.urls')),
    path("tinymce/upload-image/", TinyMCEImageUpload.as_view(), name="tinymce-upload-image"),

    # 接口url
    path('api-auth/', include('rest_framework.urls'))
]

baykeshop/apps/article/models.py
from django.db import models
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
# Create your models here.
from tinymce.fields import TinyMCEField
from baykeshop.common.models import BaseModelMixin


class BaykeArticleTags(BaseModelMixin):
    """Model definition for BaykeArticleTags."""
    name = models.CharField(_("名称"), max_length=50)

    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeArticleTags."""
        ordering = ['-add_date']
        verbose_name = _('文章标签')
        verbose_name_plural = verbose_name

    def __str__(self):
        """Unicode representation of BaykeArticleTags."""
        return self.name


class BaykeArticleCategory(BaseModelMixin):
    """Model definition for BaykeArticleCategory."""
    name = models.CharField(_("名称"), max_length=50)
    desc = models.CharField(_("描述"), max_length=150, blank=True, default="")
    keywords = models.CharField(_("关键词"), max_length=150, blank=True, default="")
    parent = models.ForeignKey(
        "self", 
        on_delete=models.CASCADE, 
        blank=True,
        null=True,
        verbose_name=_("父类")
    )
    status = models.BooleanField(default=True, verbose_name=_("状态"))
    sort = models.PositiveSmallIntegerField(default=1, verbose_name=_("排序"))

    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeArticleCategory."""
        ordering = ['sort']
        verbose_name = _('文章分类')
        verbose_name_plural = verbose_name

    def __str__(self):
        """Unicode representation of BaykeArticleCategory."""
        return self.name


class BaykeArticleContent(BaseModelMixin):
    """Model definition for BaykeArticleContent."""

    class ContentStatusChoices(models.IntegerChoices):
        DRAFT = 0, _("草稿")
        PUBLISH = 1, _("发布")

    title = models.CharField(_("标题"), max_length=100)
    desc = models.CharField(_("描述"), max_length=150, blank=True, default="")
    keywords = models.CharField(_("关键词"), max_length=150, blank=True, default="")
    category = models.ForeignKey(
        BaykeArticleCategory, 
        on_delete=models.CASCADE, 
        verbose_name=_("分类")
    )
    content = TinyMCEField(verbose_name=_("内容"))
    tags = models.ManyToManyField(BaykeArticleTags, blank=True, verbose_name=_("标签"))
    status = models.PositiveSmallIntegerField(
        choices=ContentStatusChoices.choices,
        default=1,
        verbose_name=_("状态")
    )

    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeArticleContent."""
        ordering = ['-pub_date']
        verbose_name = _('文章内容')
        verbose_name_plural = verbose_name

    def __str__(self):
        """Unicode representation of BaykeArticleContent."""
        return self.title

    def save(self, *args, **kwargs):
        from django.utils.html import strip_tags
        if not self.desc:
            self.desc = strip_tags(self.content)[:140]
        super().save(*args, **kwargs)

    @cached_property
    def next_article(self):
        # 下一篇
        try:
            return self.get_next_by_add_date()
        except BaykeArticleContent.DoesNotExist:
            return BaykeArticleContent.objects.last()
    
    @cached_property
    def previous_article(self):
        # 上一篇
        try:
            return self.get_previous_by_add_date()
        except BaykeArticleContent.DoesNotExist:
            return BaykeArticleContent.objects.first()

baykeshop/apps/user/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.db.models import Sum
# Create your models here.
from baykeshop.common.models import BaseModelMixin
from baykeshop.common.validators import validate_phone


class BaykeUser(BaseModelMixin):
    """Model definition for BaykeUser."""

    owner = models.OneToOneField(
        get_user_model(), 
        on_delete=models.CASCADE, 
        verbose_name=_("用户")
    )
    name = models.CharField(_("姓名"), max_length=50)
    phone = models.CharField(
        "手机号", 
        blank=True, 
        default="",
        max_length=11, 
        validators=[validate_phone]
    )
    sex = models.PositiveSmallIntegerField(
        choices=((0, "未知"), (1, "男"), (2, "女")), 
        default=0, 
        verbose_name=_("性别")
    )
    about = models.CharField(
        _("简介"), 
        max_length=150,
        default="菲律賓没有雪 , 馬尼拉没有愛", 
        blank=True
    )
    avatar = models.ImageField(
        _("头像"), 
        upload_to="avatar/", 
        max_length=200, 
        blank=True, 
        null=True
    )
    balance = models.DecimalField(
        _("余额"), 
        max_digits=8, 
        decimal_places=2, 
        blank=True, 
        default=0
    )

    # TODO: Define fields here

    class Meta:
        """Meta definition for BaykeUser."""
        ordering = ["-add_date"]
        verbose_name = _("用户")
        verbose_name_plural = verbose_name

    def __str__(self):
        """Unicode representation of BaykeUser."""
        return self.name


class BaykeUserBalanceLog(BaseModelMixin):
    """ 用户余额变动表 """
    
    class BalanceChangeStatus(models.IntegerChoices):
        # 收支状态
        ADD = 1, _('增加')
        MINUS = 2, _('支出')
    
    class BalanceChangeWay(models.IntegerChoices):
        # 收支渠道或方式
        PAY = 1, _('线上充值')        
        ADMIN = 2, _('管理员手动更改') 
        SHOP = 3, _('余额抵扣商品')
    
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name="用户")
    amount = models.DecimalField("金额", max_digits=15, decimal_places=2)
    change_status = models.PositiveSmallIntegerField(
        choices=BalanceChangeStatus.choices, 
        blank=True,
        null=True
    )
    change_way = models.PositiveSmallIntegerField(
        choices=BalanceChangeWay.choices, 
        default=BalanceChangeWay.ADMIN        # 默认为后台
    )

    class Meta:
        verbose_name = '余额明细'
        verbose_name_plural = verbose_name

    def __str__(self):
        return f"{self.owner.username}-{self.amount}"
    
    @classmethod
    def balance_queryset(cls, user):
        return cls.objects.filter(owner=user)
    
    @classmethod
    def add_sum_amount(cls, user):
        # 累计充值
        amount__sum = cls.balance_queryset(user).filter(
            change_status=1).aggregate(Sum('amount')).get('amount__sum')
        return round(amount__sum, 2) if amount__sum else 0
    
    @classmethod
    def minus_sum_amount(cls, user):
        # 累计消费
        amount__sum = cls.balance_queryset(user).filter(
            change_status=2).aggregate(Sum('amount')).get('amount__sum')
        return round(amount__sum, 2) if amount__sum else 0

baykeshop/apps/shop/forms.py
'''
@file            :forms.py
@Description     :表单类
@Date            :2023/09/06 11:02:42
@Author          :幸福关中 && 轻编程
@version         :v1.0
@EMAIL           :1158920674@qq.com
@WX              :baywanyun
'''

from django import forms
from django.forms import widgets
from django.contrib.admin.widgets import FilteredSelectMultiple

from .models import BaykeShopSKU, BaykeShopSpecValue


class SpecsFilteredSelectMultiple(FilteredSelectMultiple):

    def get_context(self, name, value, attrs):
        return super().get_context(name, value, attrs)


class BaykeShopSKUForm(forms.ModelForm):
    """ sku表单 """
    specs = forms.ModelMultipleChoiceField(
        queryset=BaykeShopSpecValue.objects.all(),
        widget=SpecsFilteredSelectMultiple(verbose_name="规格", is_stacked=False),
        label="规格",
        required=False,
        help_text="备注：如果为单规格商品则不必勾选，如果存在多个SKU，则必须选择"
    )

    class Meta:
        model = BaykeShopSKU
        fields = "__all__"

    def clean_specs(self):
        value_dict = {}
        specs = self.cleaned_data.get('specs')
        from collections import OrderedDict
        # 转换为有序字典
        data = specs.values('spec__name')
        data_dict = {}
        for item in data:
            data_dict[frozenset(item.items())] = item
        # 去重
        unique_data = list(OrderedDict.fromkeys(data_dict.keys()))
        # 去重后的长度小于初始长度说明存在重复
        if len(unique_data) < len(data):
            raise forms.ValidationError("一个sku不能有重复的规格，例如：一件衣服不可能既是绿色又是红色")
        
        for op in specs:
            item_dict = {}
            item_dict[op.id] = op.value
            item_dict[op.spec.name] = op.value
            value_dict.update(item_dict)
        return value_dict

baykeshop/apps/shop/api/views.py
'''
@file            :views.py
@Description     :接口相关视图
@Date            :2023/09/11 21:03:47
@Author          :幸福关中 && 轻编程
@version         :v1.0
@EMAIL           :1158920674@qq.com
@WX              :baywanyun
'''

from django.contrib import messages
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.generics import CreateAPIView
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import SessionAuthentication

from baykeshop.common.permission import IsOwnerAuthenticated
from baykeshop.apps.shop.models import BaykeShopCart, BaykeAddress
from .serializers import (
    BaykeShopCartSerializer, BaykeShopCartNumSerializer,
    BaykeShopCreateOrderSerializer, BaykeAddressSerializer,
    BaykeShopOrderCashSerializer, ConfirmReceiptSerializer
)


class BaykeShopCartCreateAPIView(CreateAPIView):
    """ 商品添加购物车 """
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]
    serializer_class = BaykeShopCartSerializer

    def get_queryset(self):
        return BaykeShopCart.objects.filter(owner=self.request.user)
    

class BaykeShopCartUpdateNumAPIView(APIView):
    """ 修改购物车商品数量 """
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated, IsOwnerAuthenticated]
    
    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer()
        serializer.is_valid(raise_exception=True)
        BaykeShopCart.objects.filter(
            id=serializer.validated_data['cartid'],
            owner=request.user
        ).update(num=serializer.validated_data['num'])
        return Response({"code": "ok"})

    def delete(self, request, *args, **kwargs):
        serializer = self.get_serializer()
        serializer.is_valid(raise_exception=True)
        BaykeShopCart.objects.filter(
            id=serializer.validated_data['cartid'],
            owner=request.user,
        ).delete()
        return Response({"code": "ok"})

    def get_serializer(self):
        serializer = BaykeShopCartNumSerializer(
            data=self.request.data, 
            context={"request": self.request}
        )
        return serializer
    

class BaykeShopOrderCreateAPIView(CreateAPIView):
    """ 创建订单 """
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]
    serializer_class = BaykeShopCreateOrderSerializer


class BaykeShopOrderCashAPIView(APIView):
    """ 立即支付 """
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]

    def post(self, request, *args, **kwargs):
        serializer = BaykeShopOrderCashSerializer(
            data=request.data, 
            context={"request": self.request}
        )
        serializer.is_valid(raise_exception=True)
        instance=serializer.get_instance(serializer.validated_data['orderid'])
        serializer.update(instance, serializer.validated_data)
        return Response(serializer.data)


class BaykeAddressViewSet(viewsets.ModelViewSet):
    """ 地址增删改查 """
    serializer_class = BaykeAddressSerializer
    permission_classes = [IsAuthenticated, IsOwnerAuthenticated]

    def get_queryset(self):
        return BaykeAddress.objects.filter(owner=self.request.user)
    
    def perform_create(self, serializer):
        self.save_only_default(serializer)
        return super().perform_create(serializer)
    
    def perform_update(self, serializer):
        self.save_only_default(serializer)
        return super().perform_update(serializer)
    
    def save_only_default(self, serializer):
        # 处理默认收货地址只能有一个
        if serializer.validated_data['is_default']:
            self.get_queryset().filter(is_default=True).update(is_default=False)


class ConfirmReceiptAPIView(APIView):
    """ 确认收货接口 """
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]

    def post(self, request, *args, **kwargs):
        serializer = ConfirmReceiptSerializer(data=request.data, context={'request': request})
        serializer.is_valid(raise_exception=True)
        order = serializer.get_order(serializer.validated_data['orderid'])
        order.update(status=4)
        messages.success(request, '确认收货成功！')
        return Response({'code':'ok'})

baykeshop/apps/shop/templates/shop/menmber/address.html
{% extends 'shop/menmber/menmber.html' %}


{% block title %}
	我的地址
{% endblock %}
	

{% block breadcrumb %}
<div class="container my-4">
	<nav class="breadcrumb is-marginless is-small" aria-label="breadcrumbs">
		<ul>
			<li><a href="{% url 'shop:home' %}">首页</a></li>
			<li class="is-active"><a href="#" aria-current="page">地址管理</a></li>
		</ul>
	</nav>
</div>
{% endblock %}

{% block menmber_title %}我的地址{% endblock %}

{% block menmber %}
{% include 'shop/address.html' with update=True delete=True %}
{% endblock %}

baykeshop/apps/shop/templates/shop/menmber/balance.html
{% extends 'shop/menmber/menmber.html' %}

{% load shoptags %}

{% block menmber_title %}我的余额{% endblock %}

{% block menmber %}
<div class="box is-radiusless is-shadowless">
    <div class="columns pl-6 pr-6 pt-3">
        <div class="column">
            <p class=" has-text-grey-light">账户可用余额</p>
            <h1 class="is-size-4">¥ {{ request.user.baykeuser.balance }}</h1> 
        </div>
        <div class="column">
            <p class=" has-text-grey-light">累计充值</p>
            <h1 class=" is-size-4">¥ {{ add_sum_amount }}</h1>
        </div>
        <div class="column">
            <p class=" has-text-grey-light">累计消费</p>
            <h1 class=" is-size-4">¥ {{ minus_sum_amount }}</h1>
        </div>
    </div>
    <div class=" dropdown-divider"></div>

    <div class="table-container pl-4 pr-4">
        <table class="table is-fullwidth is-hoverable">
            <tbody>
                <thead>
                    <th>序号</th>
                    <th>收支状态</th>
                    <th>收支金额</th>
                    <th>收支渠道</th>
                    <th>时间</th>
                </thead>
                {% for balance in balance_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td class="{% if balance.change_status == 1 %}  has-text-success-dark {% else %} has-text-danger-dark {% endif %}">
                        {{ balance.get_change_status_display }}
                    </td>
                    <td class="{% if balance.change_status == 1 %}  has-text-success-dark {% else %} has-text-danger-dark {% endif %}">
                        {% if balance.change_status == 1 %}  + {% else %} - {% endif %}{{ balance.amount }}
                    </td>
                    <td class="{% if balance.change_status == 1 %}  has-text-success-dark {% else %} has-text-danger-dark {% endif %}">
                        {{ balance.get_change_way_display }}
                    </td>
                    <td class="{% if balance.change_status == 1 %}  has-text-success-dark {% else %} has-text-danger-dark {% endif %}">
                        {{ balance.add_date }}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

baykeshop/apps/shop/templates/shop/menmber/menmber.html
{% extends 'shop/base.html' %}

{% load static %}

{% block breadcrumb %}
<div class="container my-4">
	<nav class="breadcrumb is-marginless is-small" aria-label="breadcrumbs">
		<ul>
			<li><a href="{% url 'shop:home' %}">首页</a></li>
			<li class="is-active"><a href="#" aria-current="page">{{ title }}</a></li>
		</ul>
	</nav>
</div>
{% endblock %}

{% block section %}
<div class="container">
    <div class="columns">
      <div class="column is-2">
        <div class="box is-radiusless is-marginless is-flex is-flex-direction-column is-align-items-center">
          <figure class="image is-64x64">
            <img class="is-rounded" src="
                {% if request.user.baykeuser.avatar %}
                {{ request.user.baykeuser.avatar.url }}
                {% else %}{% static 'img/wx.jpg' %}{% endif %}">
          </figure>
          <p class="mt-2">
            {% if request.user.baykeuser.name %}
                {{ request.user.baykeuser.name }}
            {% else %}
                {{ request.user.username }}
            {% endif %}
          </p>
        </div>
        <div class="box is-radiusless">
          <aside class="menu">
            <p class="menu-label">
              账户管理
            </p>
            <ul class="menu-list">
              <li><a href="{% url 'shop:menmber' %}"
                  class="{% if request.path == '/menmber/' %} is-active {% endif %}">个人信息</a></li>
              <li><a href="{% url 'shop:balance-log' %}"
                  class="{% if 'balance' in request.path %} is-active {% endif %}">我的余额</a></li>
              <li><a href="{% url 'shop:address' %}"
                  class="{% if 'address' in request.path %} is-active {% endif %}">地址管理</a></li>
            </ul>
            <p class="menu-label">订单管理</p>
            <ul class="menu-list">
              <li><a href="{% url 'shop:orders-list' %}" class="{% if 'orders' in request.path %} is-active {% endif %}">我的订单</a></li>
            </ul>
  
          </aside>
        </div>
  
      </div>
      <div class="column">
        <div class="box is-radiusless">
          <h1 class="is-size-4">
            {% block menmber_title %}个人中心{% endblock %}
          </h1>
          <div class="dropdown-divider"></div>
          {% block menmber %}
          <div class="columns pt-3 pb-3">
            <div class="column is-2">个人信息</div>
            {% include 'shop/menmber/userinfo.html' %}
          </div>
          {% endblock %}
        </div>
      </div>
    </div>
</div>  
{% endblock %}

baykeshop/apps/shop/templates/shop/menmber/orders-detail.html
{% extends 'shop/menmber/menmber.html' %}

{% load shoptags %}

{% block breadcrumb %}
<div class="container my-4">
	<nav class="breadcrumb is-marginless is-small" aria-label="breadcrumbs">
		<ul>
			<li><a href="{% url 'shop:home' %}">首页</a></li>
			<li class="is-active"><a href="#" aria-current="page">{{ title }}</a></li>
		</ul>
	</nav>
</div>
{% endblock %}


{% block menmber %}
{% ordersku order.baykeshopordersku_set.all as order_compute %}
<div class="box is-radiusless is-marginless pt-6" id="orderStatus">
    <b-steps v-model="activeStep" :has-navigation="false">
        <b-step-item label="待付款" icon="account-key" :clickable="false"></b-step-item>
        <b-step-item label="待发货" icon="car" :clickable="false"></b-step-item>
        <b-step-item label="待收货" icon="account-plus" :clickable="false"></b-step-item>
        <b-step-item label="待评价" icon="comment-plus" :clickable="false"></b-step-item>
        <b-step-item label="已完成" icon="store" :clickable="false"></b-step-item>
        <!-- <b-step-item label="已关闭" icon="close" :clickable="false"></b-step-item>
        <b-step-item label="退款中" icon="store" :clickable="false"></b-step-item> -->
    </b-steps>
</div>

<div class="box is-radiusless is-marginless is-shadowless">
    <h1 class=" is-size-5">订单信息</h1>
    <div class="dropdown-divider"></div>
    <ul style="line-height: 30px;">
        <li>订单编号：{{ order.order_sn }}</li>

        <li>订单日期：{{ order.add_date }}</li>

        <li>支付状态：{{ order.get_status_display }}</li>

        <li>支付方式：{{ order.get_paymethod_display }}</li>

        <li>订单金额：¥{{ order_compute.total_price }}</li>

        <li>订单留言：{{ order.mark }}</li>
    </ul>
</div>
<div class="box is-radiusless is-marginless1 is-shadowless">
    <h1 class=" is-size-5">收货信息</h1>
    <div class="dropdown-divider"></div>
    <ul style="line-height: 30px;">
        <li>签收人：{{ order.name }}</li>
        <li>手机号：{{ order.phone }}</li>
        <li>收货地址：{{ order.address }}</li>
    </ul>
</div>

<div class="box is-radiusless mb-4 is-shadowless">
    <h1 class=" is-size-5">商品信息</h1>
    <div class="dropdown-divider"></div>
    {% for sku in order.baykeshopordersku_set.all %}
    <div class="is-flex is-justify-content-space-between">
        <div>
            <figure class=" image is-96x96">
                <img src="{{ sku.sku_json.img }}" alt="{{ sku.sku_json.title }}" srcset="">
            </figure>
        </div>
        <div
            class="has-background-danger1 is-flex is-flex-direction-column is-justify-content-center is-flex-grow-1 pl-3 pr-3">
            <h1 class="has-text-weight-bold">{{ sku.sku_json.title }}</h1>
            <div class="is-flex">
                {% for op, value in sku.sku_json.specs.items %}
                <span class="mr-3 has-text-grey-light">{{ op }}:{{ value }}</span>
                {% endfor %}
            </div>
        </div>
        <div class="has-background-danger1 is-flex is-justify-content-center is-align-items-center">
            <p class="has-text-danger-dark">¥ {{ sku.sku_json.price }} x {{ sku.count }}</p>
        </div>
    </div>
    <div class="dropdown-divider"></div>
    {% endfor %}
    {% order_action order %}
</div>

{% endblock %}


{% block extravue %}
<script>
    var orderStatus = new Vue({
        el: '#orderStatus',
        delimiters: ['{$', '$}'],
        data: {
            activeStep: 0,
        },
        created() {
            this.orderStatusMethod()
        },
        methods: {
            orderStatusMethod() {
                switch (Number('{{ order.status }}')) {
                    case 1:
                        this.activeStep = 0;
                        break;
                    case 2:
                        this.activeStep = 1;
                        break;
                    case 3:
                        this.activeStep = 2;
                        break;
                    case 4:
                        this.activeStep = 3;
                        break;
                    case 5:
                        this.activeStep = 4;
                        break;
                    case 6:
                        this.activeStep = 5;
                        break;
                    case 7:
                        this.activeStep = 6;
                        break;
                }
            },
        }
    })
</script>
{% endblock %}

baykeshop/apps/shop/templates/shop/menmber/orders.html
{% extends 'shop/menmber/menmber.html' %}

{% load bayketags shoptags %}

{% block breadcrumb %}
<div class="container my-4">
	<nav class="breadcrumb is-marginless is-small" aria-label="breadcrumbs">
		<ul>
			<li><a href="{% url 'shop:home' %}">首页</a></li>
			<li class="is-active"><a href="#" aria-current="page">{{ title }}</a></li>
		</ul>
	</nav>
</div>
{% endblock %}

{% block menmber %}
<div class="tabs is-boxed is-fullwidth">
    <ul>
        <li class="{% if 'status' not in request.get_full_path or status == '' %} is-active {% endif %}" ><a href="{% url 'shop:orders-list' %}">全部订单</a></li>
        <li class="{% if 'status=1' in request.get_full_path %} is-active {% endif %}"><a href="{% url 'shop:orders-list' %}?status=1">待付款</a></li>
        <li class="{% if 'status=2' in request.get_full_path %} is-active {% endif %}"><a href="{% url 'shop:orders-list' %}?status=2">待发货</a></li>
        <li class="{% if 'status=3' in request.get_full_path %} is-active {% endif %}"><a href="{% url 'shop:orders-list' %}?status=3">待收货</a></li>
        <li class="{% if 'status=4' in request.get_full_path %} is-active {% endif %}"><a href="{% url 'shop:orders-list' %}?status=4">待评价</a></li>
        <li class="{% if 'status=5' in request.get_full_path %} is-active {% endif %}"><a href="{% url 'shop:orders-list' %}?status=5">已完成</a></li>
    </ul>
</div>
{% for order in page_obj %}
<div class="box has-background-light is-shadowless">
    <div class="is-flex is-justify-content-space-between">
        <div class=" has-text-grey-light1">订单日期：{{ order.add_date }}</div>
        <div class=" has-text-danger-dark">
            {{ order.get_status_display }}
        </div>
    </div>
    <div class="dropdown-divider"></div>
    {% for sku in order.baykeshopordersku_set.all %}
    <div class="is-flex is-justify-content-space-between">
        <div>
            <figure class=" image is-96x96">
                <img src="{{ sku.sku_json.img }}" alt="{{ sku.sku_json.title }}" srcset="">
            </figure>
        </div>
        <div class="has-background-danger1 is-flex is-flex-direction-column is-justify-content-center is-flex-grow-1 pl-3 pr-3">
            <h1 class="has-text-weight-bold">{{ sku.sku_json.title }}</h1>
            <div class="is-flex">
                {% for op, value in sku.sku_json.specs.items %}
                <span class="mr-3 has-text-grey-light">{{ op }}:{{ value }}</span>
                {% endfor %}
            </div>
        </div>
        <div class="has-background-danger1 is-flex is-justify-content-center is-align-items-center">
            <p class="has-text-danger-dark">¥ {{ sku.sku_json.price }} x {{ sku.count }}</p>
        </div>
    </div>
    <div class="dropdown-divider"></div>
    {% endfor %}
    {% order_action order %}
</div>
{% endfor %}
{% pagination page_obj %}
{% endblock %}