baykeproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include("baykeshop.urls")),

    *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
]

baykeshop/apps/shop/api/urls.py
'''
@file            :urls.py
@Description     :接口url
@Date            :2023/09/11 21:08:48
@Author          :幸福关中 && 轻编程
@version         :v1.0
@EMAIL           :1158920674@qq.com
@WX              :baywanyun
'''

from django.urls import path
from rest_framework.routers import DefaultRouter
from . import views

app_name = "shopapi"

router = DefaultRouter()

router.register('address', views.BaykeAddressViewSet, basename='address')

urlpatterns = [
    path(
        'create-cart/', 
        views.BaykeShopCartCreateAPIView.as_view(), 
        name='create-cart'
    ),
    path(
        'update-cart-num/', 
        views.BaykeShopCartUpdateNumAPIView.as_view(), 
        name='update-cart-num'
    ),
    path(
        'del-cart/', 
        views.BaykeShopCartUpdateNumAPIView.as_view(), 
        name='del-cart'
    ),
    path(
        'create-order/', 
        views.BaykeShopOrderCreateAPIView.as_view(), 
        name='create-order'
    ),
    path(
        'cash-order/', 
        views.BaykeShopOrderCashAPIView.as_view(), 
        name='cash-order'
    ),
    path(
        'confirm-receipt/', 
        views.ConfirmReceiptAPIView.as_view(), 
        name='confirm-receipt'
    ),
    *router.urls
]

baykeshop/apps/system/urls.py
from django.urls import path, include
from . import views

app_name = 'system'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('api/', include('baykeshop.apps.system.api.urls'))
]

baykeshop/urls.py
from django.urls import path, include
from tinymce.views import TinyMCEImageUpload

urlpatterns = [
    path('', include('baykeshop.apps.shop.urls')),
    path('article/', include('baykeshop.apps.article.urls')),
    path('system/', include('baykeshop.apps.system.urls')),
    path('user/', include('baykeshop.apps.user.urls')),
    path('captcha/', include('captcha.urls')),
    path("tinymce/upload-image/", TinyMCEImageUpload.as_view(), name="tinymce-upload-image"),

    # 接口url
    path('api-auth/', include('rest_framework.urls'))
]

baykeshop/apps/shop/api/views.py
'''
@file            :views.py
@Description     :接口相关视图
@Date            :2023/09/11 21:03:47
@Author          :幸福关中 && 轻编程
@version         :v1.0
@EMAIL           :1158920674@qq.com
@WX              :baywanyun
'''

from django.contrib import messages
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.generics import CreateAPIView
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import SessionAuthentication

from baykeshop.common.permission import IsOwnerAuthenticated
from baykeshop.apps.shop.models import BaykeShopCart, BaykeAddress
from .serializers import (
    BaykeShopCartSerializer, BaykeShopCartNumSerializer,
    BaykeShopCreateOrderSerializer, BaykeAddressSerializer,
    BaykeShopOrderCashSerializer, ConfirmReceiptSerializer
)


class BaykeShopCartCreateAPIView(CreateAPIView):
    """ 商品添加购物车 """
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]
    serializer_class = BaykeShopCartSerializer

    def get_queryset(self):
        return BaykeShopCart.objects.filter(owner=self.request.user)
    

class BaykeShopCartUpdateNumAPIView(APIView):
    """ 修改购物车商品数量 """
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated, IsOwnerAuthenticated]
    
    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer()
        serializer.is_valid(raise_exception=True)
        BaykeShopCart.objects.filter(
            id=serializer.validated_data['cartid'],
            owner=request.user
        ).update(num=serializer.validated_data['num'])
        return Response({"code": "ok"})

    def delete(self, request, *args, **kwargs):
        serializer = self.get_serializer()
        serializer.is_valid(raise_exception=True)
        BaykeShopCart.objects.filter(
            id=serializer.validated_data['cartid'],
            owner=request.user,
        ).delete()
        return Response({"code": "ok"})

    def get_serializer(self):
        serializer = BaykeShopCartNumSerializer(
            data=self.request.data, 
            context={"request": self.request}
        )
        return serializer
    

class BaykeShopOrderCreateAPIView(CreateAPIView):
    """ 创建订单 """
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]
    serializer_class = BaykeShopCreateOrderSerializer


class BaykeShopOrderCashAPIView(APIView):
    """ 立即支付 """
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]

    def post(self, request, *args, **kwargs):
        serializer = BaykeShopOrderCashSerializer(
            data=request.data, 
            context={"request": self.request}
        )
        serializer.is_valid(raise_exception=True)
        instance=serializer.get_instance(serializer.validated_data['orderid'])
        serializer.update(instance, serializer.validated_data)
        return Response(serializer.data)


class BaykeAddressViewSet(viewsets.ModelViewSet):
    """ 地址增删改查 """
    serializer_class = BaykeAddressSerializer
    permission_classes = [IsAuthenticated, IsOwnerAuthenticated]

    def get_queryset(self):
        return BaykeAddress.objects.filter(owner=self.request.user)
    
    def perform_create(self, serializer):
        self.save_only_default(serializer)
        return super().perform_create(serializer)
    
    def perform_update(self, serializer):
        self.save_only_default(serializer)
        return super().perform_update(serializer)
    
    def save_only_default(self, serializer):
        # 处理默认收货地址只能有一个
        if serializer.validated_data['is_default']:
            self.get_queryset().filter(is_default=True).update(is_default=False)


class ConfirmReceiptAPIView(APIView):
    """ 确认收货接口 """
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]

    def post(self, request, *args, **kwargs):
        serializer = ConfirmReceiptSerializer(data=request.data, context={'request': request})
        serializer.is_valid(raise_exception=True)
        order = serializer.get_order(serializer.validated_data['orderid'])
        order.update(status=4)
        messages.success(request, '确认收货成功！')
        return Response({'code':'ok'})

baykeshop/apps/shop/views.py
from typing import Any
from django.db import models
from django.db.models.query import QuerySet
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.detail import SingleObjectMixin
from django.utils.functional import cached_property
from django.urls import reverse
from rest_framework.renderers import TemplateHTMLRenderer
# Create your views here.
from baykeshop.common.mixins import LoginRequiredMixin
from baykeshop.common.renderers import TemplateHTMLRenderer
from baykeshop.apps.shop.api.views import BaykeAddressViewSet
from baykeshop.apps.user.models import BaykeUserBalanceLog
from baykeshop.apps.system.models import (
    BaykeADPosition, BaykeComment, BaykeADSpace
) 
from baykeshop.apps.shop.models import (
    BaykeShopCategory, BaykeShopSPU, BaykeShopSKU, BaykeShopCart,
    BaykeShopOrder
)


    
class SPUAliasAnnotateMixin:
    
    def alias_annotate_queryset(self, queryset):
        return queryset.alias(
            price=models.Min('baykeshopsku__price'),
            sales=models.Sum('baykeshopsku__sales')
        ).annotate(
            price=models.F('price'),
            sales=models.F('sales')
        )


class HomeTemplateView(TemplateView, SPUAliasAnnotateMixin):
    """ 首页 """
    template_name = "shop/index.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = '开源嫖娼系统 联系飞机 @Ben_Bird '
        context['banners'] = self.banners
        context['floors'] = self.get_floors
        return context
    
    @cached_property
    def get_floors(self):
        cates = BaykeShopCategory.objects.filter(is_nav=True, parent__isnull=True)
        for cate in cates:
            subcates = cate.baykeshopcategory_set.filter(is_nav=True)
            cate.spus = self.alias_annotate_queryset(
                BaykeShopSPU.objects.filter(category__in=subcates).distinct()
            )[:10]
        return cates
    
    @cached_property
    def banners(self):
        instance, iscreated = BaykeADPosition.objects.get_or_create(
            name="商城首页轮播图广告位",
            slug="shophomebanner",
            desc="商城首页轮播图广告位【多图】"
        )
        if iscreated:
            BaykeADSpace.objects.create(
                name="轮播图1",
                slug="shopbanner",
                space="img",
                position=instance,
                img="common/ad/banner.jpg"
            )
        return BaykeADPosition.get_position_spaces(slug="shophomebanner")
    

class BaykeShopSPUListView(ListView, SPUAliasAnnotateMixin):
    """ 全部妹子 """

    model = BaykeShopSPU
    template_name = "shop/list.html"
    paginate_by = 20
    paginate_orphans = 4
    ordering = "add_date"

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset().filter(status=True)
        return self.alias_annotate_queryset(queryset)
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['parent_cates'] = self.get_baykeshopcategory
        context['sub_cates'] = self.get_baykeshopcategory_set
        context['title'] = "全部妹子"
        context['sort_params'] = self.get_sort_params
        return context
    
    @cached_property
    def get_baykeshopcategory(self):
        parent_cates = BaykeShopCategory.objects.filter(
            status=True, parent__isnull=True
        )
        return parent_cates
    
    @cached_property
    def get_baykeshopcategory_set(self):
        queryset = BaykeShopCategory.objects.none()
        if self.get_baykeshopcategory.exists():
            queryset = self.get_baykeshopcategory.first() \
                .baykeshopcategory_set.filter(status=True)
        return queryset
    
    def alias_annotate_queryset(self, queryset):
        # 对注解过的queryset进行排序
        return super().alias_annotate_queryset(queryset).order_by(self.get_sort_params)
    
    @cached_property
    def get_sort_params(self):
        # 排序字段
        return self.request.GET.get('ordering', self.ordering)
        
    def get_absolute_url(self):
        return reverse('shop:goods')


class BaykeShopCategoryDetailView(SingleObjectMixin, BaykeShopSPUListView):
    """ 商品分类详情列表 """

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(
            queryset=BaykeShopCategory.objects.filter(status=True)
        )
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sub_cates'] = self.get_baykeshopcategory_set
        context['title'] = self.object.name
        return context

    def get_queryset(self) -> QuerySet[Any]:
        queryset = self.object.baykeshopspu_set.filter(status=True)
        if self.object.parent is None:
            queryset = BaykeShopSPU.objects.filter(
                status=True, 
                category__in=self.object.baykeshopcategory_set.filter(status=True)
            )
        return self.alias_annotate_queryset(queryset)
    
    @cached_property
    def get_baykeshopcategory_set(self):
        queryset = self.object.baykeshopcategory_set.filter(status=True)
        if self.object.parent:
            queryset = self.object.parent.baykeshopcategory_set.filter(status=True)
        return queryset
    
    def get_absolute_url(self):
        return reverse('shop:cate-detail', kwargs={'pk': self.pk})


class BaykeShopSPUSearchView(BaykeShopSPUListView):
    """ 搜索视图 """

    def get_queryset(self) -> QuerySet[Any]:
        words = self.request.GET.get('words', '')
        return super().get_queryset().filter(
            models.Q(title__icontains=words)|
            models.Q(subtitle__icontains=words)|
            models.Q(content__icontains=words)
        )

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = self.request.GET.get('words')
        return context


class BaykeShopSPUDetailView(DetailView):
    """ 商品详情页 """
    model = BaykeShopSPU
    context_object_name = "spu"
    template_name = "shop/detail.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = self.get_object().title
        context['spuhots'] = BaykeShopSPU.get_hots()
        context['comments'] = self.get_page_comments()
        return context

    def get_absolute_url(self):
        return reverse('shop:spu-detail', kwargs={'pk': self.pk})
    
    def get_comments(self):
        # 商品评价
        comments = BaykeComment.objects.filter(tag=str(self.get_object().id))
        return comments
    
    def get_page_comments(self):
        # 评价分页
        comments = self.get_comments()
        from django.core.paginator import Paginator
        paginator = Paginator(comments, 20)
        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        return page_obj
    

class BaykeShopCartListView(LoginRequiredMixin, ListView):
    """ 购物车列表 """
    model = BaykeShopCart
    template_name = "shop/carts.html"
    context_object_name = "carts"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = '购物车'
        context['carts_values'] = self.get_queryset_values
        return context

    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(owner=self.request.user)
    
    @cached_property
    def get_queryset_values(self):
        cart_queryset = self.get_queryset().values('id', 'sku', 'num', 'add_date')
        for cart in cart_queryset:
            sku = BaykeShopSKU.objects.get(id=cart['sku'])
            cart['sku'] = {
                "id": sku.id,
                "title": sku.spu.title,
                "price": sku.price,
                "img": sku.img.url,
                "cost_price": sku.cost_price,
                "discount_price": sku.discount_price,
                "stock": sku.stock,
                "sales": sku.sales,
                "code": sku.code,
                "specs": { key: value for key, value in sku.specs.items() if not key.isdigit() }
            }
        return list(cart_queryset)
    

class BaykeShopOrderCashDetailView(LoginRequiredMixin, DetailView):
    """ 订单收银台 """
    model = BaykeShopOrder
    template_name = "shop/ordercash.html"
    context_object_name = "order"

    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(owner=self.request.user)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = "收银台"
        return context
    

class BaykeUserMemberView(LoginRequiredMixin, TemplateView):
    """ 个人中心 """
    template_name = "shop/member/member.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = "个人中心"
        return context
    

class BaykeAddressView(BaykeAddressViewSet):
    """ 用户地址 """
    renderer_classes = [TemplateHTMLRenderer, ]
    
    def list(self, request, *args, **kwargs):
        response = super().list(request, *args, **kwargs)
        response.template_name = "shop/member/address.html"
        return response
    

class BaykeShopOrderListView(LoginRequiredMixin, ListView):
    """ 我的订单 """
    model = BaykeShopOrder
    template_name = "shop/member/orders.html"
    paginate_by = 5

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = '我的订单'
        return context

    def get_queryset(self) -> QuerySet[Any]:
        status = self.request.GET.get('status')
        queryset = super().get_queryset().filter(owner=self.request.user)
        if status:

baykeshop/apps/shop/templates/shop/banners.html
<div id="carousel" class="container">
    <template>
        <b-carousel :pause-info="false">
            {% for banner in banners %}
            <b-carousel-item>
                <section class="hero is-medium">
                    <a class="image" href="{{ banner.target }}">
                        <img width="100%" src="{{ banner.img.url }}" alt="{{ banner.remark }}"> 
                    </a>
                </section>
            </b-carousel-item>
            {% endfor %}
        </b-carousel>
    </template>
</div>
<script>
    var carousel = new Vue({
        el: '#carousel',
        delimiters: ['{$', '$}'],
        data: {},
    })
</script>

baykeshop/apps/shop/templates/shop/base.html
{% extends 'system/base_site.html' %}

{% block header %}
{% include 'shop/header.html' %}
{% endblock %}
    

baykeshop/apps/shop/templates/shop/detail.html
{% extends 'shop/base.html' %}

{% load bayketags shoptags %}

{% block breadcrumb %}
<div class="container my-4">
	<nav class="breadcrumb is-marginless is-small" aria-label="breadcrumbs">
		<ul>
			<li><a href="{% url 'shop:home' %}">首页</a></li>
            {% for cate in spu.category.all %}
            <li>
                <a href="">{{ cate.name }}</a>
            </li>
            {% endfor %}
			<li class="is-active"><a href="#" aria-current="page">{{ spu.title }}</a></li>
		</ul>
	</nav>
</div>
{% endblock %}

{% block section %}
<section class="section1">
    <div class="container">
        <div class="columns">
            <div class="column is-3">
                {% spubanners spu %}
            </div>
            <div class="column">
                <h1 class="title is-size-4">{{ spu.title }}</h1>
                <p class="subtitle">{{ spu.subtitle }}</p>
                {% spuspecs spu %}
                <div class="box is-radiusless mt-3" id="goodsContent">
                    <b-tabs class="block">
                        <b-tab-item label="商品详情">
                            <div class="content">
                                {{ spu.content|safe }}
                            </div>
                        </b-tab-item>
                        <b-tab-item label="商品评价">
                            {% comments_score spu as commentScore %}
                            <div class="is-flex is-justify-content-space-between">
                                <div class="">满意度：{{ commentScore.rate }}%</div>
                                <div class="is-flex is-align-items-center">
                                    <span> 评分：</span>
                                    <b-rate 
                                        :value="{{ commentScore.score_avg }}" 
                                        disabled
                                        size="is-small" 
                                        custom-text="{{ commentScore.score_avg }}分">
                                    </b-rate>
                                </div>
                            </div>
                            <div class="dropdown-divider"></div>
                            {% for comment in comments %}
                            <article class="media">
                                <figure class="media-left">
                                    <p class="image is-32x32">
                                        <img class="is-rounded" src="{% if comment.owner.baykeuser.avatar %}{{ comment.owner.baykeuser.avatar.url }}{% endif %}">
                                    </p>
                                </figure>
                                <div class="media-content">
                                    <p>
                                        {{ comment.owner.username }}
                                        <b-rate size="is-small" :value="{{ comment.score }}" disabled custom-text="{{ comment.score }}分"></b-rate>
                                    </p>
                                    <p class=" is-size-7">{{ comment.add_date|timesince }}前</p>
                                    <p class=" has-text-grey-light">{{ comment.content }}</p>
                                    
                                    {% if comment.reply %}
                                    <div class="box is-shadowless has-background-light">
                                        <span class="has-text-danger-dark">商家回复：</span> {{ comment.reply }}
                                    </div>
                                    {% endif %}
                                </div>
                                
                            </article>
                            {% endfor %}
                            {% if comments.has_previous or comments.has_next %}
                            <div class=" dropdown-divider"></div>
                            {% endif %}
                            <nav class="pagination is-small" role="navigation" aria-label="pagination">
                                {% if comments.has_previous %}
                                <a class="pagination-previous" href="?page={{ comments.previous_page_number }}">Previous</a>
                                {% endif %}
                                {% if comments.has_next %}
                                <a class="pagination-next" href="?page={{ page_obj.next_page_number }}">Next page</a>
                                {% endif %}
                            </nav>
                        </b-tab-item>
                    </b-tabs>
                </div>
            </div>
            <div class="column is-2">
                <div class="box is-radiusless is-shadowless">
                    <h1 class="has-text-centered has-text-weight-bold">热门商品</h1> 
                    <div class=" dropdown-divider"></div>
                    {% for spu in spuhots %}
                        {% spubox spu %}
                        <div class="dropdown-divider mb-3"></div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}


{% block extravue %}
    <script>
        var goodsContent = new Vue({
            el: "#goodsContent",
            delimiters: ['{$', '$}'],
            data: {},
        })
    </script>
{% endblock %}
    

baykeshop/apps/shop/templates/shop/header.html
{% load bayketags shoptags %}
<header id="header">
    <div class="has-background-black-ter">
        <div class="container">
            <div class="is-flex is-justify-content-space-between" style="line-height: 40px;">
                <div class="has-text-light is-size-7">老色批们快来嫖娼!</div>
                <div class="is-flex">
                    {% if request.user.is_authenticated %}
                    <b-dropdown :triggers="['hover']" aria-role="list" style="z-index: 100;">
                        <template #trigger>
                            <div class=" is-clickable has-text-light is-size-7">
                                <span>欢迎您，{{ request.user.username }}</span>
                                <span class="icon"><i class="mdi mdi-menu-down"></i></span>
                            </div>
                        </template>
                        <b-dropdown-item aria-role="listitem" has-link>
                            <a href="{% url 'shop:member' %}">
                                <span class="icon"><i class="mdi mdi-account-box-outline"></i></span>
                                个人中心
                            </a>
                        </b-dropdown-item>
                        <b-dropdown-item aria-role="listitem" has-link>
                            <a href="{% url 'shop:orders-list' %}">
                                <span class="icon"><i class="mdi mdi-basket-plus-outline"></i></span>
                                我的订单
                            </a>
                        </b-dropdown-item>
                        <div class="dropdown-divider"></div>
                        <b-dropdown-item aria-role="listitem" has-link>
                            <a href="{% url 'system:logout' %}">
                                <span class="icon"><i class="mdi mdi-logout"></i></span>
                                退出
                            </a> 
                        </b-dropdown-item>
                    </b-dropdown>
                    {% else %}
                    <a class="has-text-light is-size-7" href="{% url 'system:login' %}">
                        <span class="icon"><i class="mdi mdi-login"></i></span>
                        <span>登录</span>
                    </a>
                    <span class="pl-2 pr-1">|</span>
                    <a class="has-text-light is-size-7" href="{% url 'system:register' %}">
                        <span class="icon"><i class="mdi mdi-account-plus-outline"></i></span>
                        <span>注册</span>
                    </a>
                    {% endif %}
                    <div class="has-background-grey-darker ml-4">
                        <a class="pl-4 pr-5 has-text-light is-size-7" href="{% url 'shop:carts' %}">
                            <span class="icon"><i class="mdi mdi-cart-outline"></i></span>
                            购物车({$ cartcount $})
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <template>
        <b-navbar spaced shadow wrapper-class="container">
            <template #brand>
                <b-navbar-item tag="div">
                    <h1 class="title">嫖娼系统</h1>
                </b-navbar-item>
            </template>
            <template #start>
                <b-navbar-item href="{% url 'shop:home' %}">
                    首页
                </b-navbar-item>
                <b-navbar-item href="{% url 'shop:goods' %}" 
                    {% if title == '全部妹子' %} active {% endif %}>
                    全部妹子
                </b-navbar-item>
                {% shopcates as shopnavs %}
                {% for cate in shopnavs %}
                <b-navbar-dropdown label="{{ cate.name }}">
                    {% for subcate in cate.baykeshopcategory_set.all %}
                    <b-navbar-item href="{% url 'shop:cate-detail' subcate.id %}" 
                        {% if title == subcate.name %} active {% endif %}>
                        {{ subcate.name }}
                    </b-navbar-item>
                    {% endfor %}
                </b-navbar-dropdown>
                {% endfor %}
                <b-navbar-item href="{% url 'baykearticle:article-list' %}">
                    嫖娼心得
                </b-navbar-item>
            </template>

            <template #end>
                <b-navbar-item tag="div">
                    <form action="{% url 'shop:search' %}" method="get">
                        {% csrf_token %}
                        <b-field>
                            <b-input placeholder="请输入商品关键词搜索" type="search" name="words" icon="magnify" value="{{ request.GET.words }}">
                            </b-input>
                            <p class="control">
                                <b-button type="is-primary" label="搜索" native-type="submit" />
                            </p>
                        </b-field>
                    </form>
                </b-navbar-item>
            </template>
        </b-navbar>
    </template>
</header>

<script>
    var header = new Vue({
        el: '#header',
        delimiters: ['{$', '$}'],
        data: {
            cartcount: Number('{% cartscount request %}')
        },
    })
</script>

baykeshop/apps/shop/templates/shop/list.html
{% extends 'shop/base.html' %}

{% load bayketags shoptags %}

{% block breadcrumb %}
<div class="container my-4">
	<nav class="breadcrumb is-marginless is-small" aria-label="breadcrumbs">
		<ul>
			<li><a href="{% url 'shop:home' %}">首页</a></li>
			<li class="is-active"><a href="#" aria-current="page">{{ title }}</a></li>
		</ul>
	</nav>
</div>
{% endblock %}

{% block section %}
<section class="section1">
    <div class="container">
        {% include 'shop/filters.html' %}
        <div class="columns is-multiline is-mobile">
            {% for spu in page_obj %}
            <div class="column is-3-desktop is-6-mobile">
                {% spubox spu %}
            </div>
            {% endfor %}
        </div>
        {% pagination page_obj %}
    </div>
</section>
{% endblock %}